DROP TABLE IF EXISTS PHONES;
DROP TABLE IF EXISTS USUARIOS;


CREATE TABLE USUARIOS (
    ID NUMERIC AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    CORREO VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL,
    FECHA_ACTUALIZACION DATETIME,
    ULTIMO_INGRESO DATETIME,
    USUARIO_ACTIVO BOOLEAN
);

CREATE TABLE PHONES(
    ID_PHONES NUMERIC AUTO_INCREMENT PRIMARY KEY,
    NUMBER VARCHAR(255) NOT NULL ,
    CITY_CODE VARCHAR(5) NOT NULL,
    COUNTRY_CODE VARCHAR(5),
    ID_USUARIO NUMERIC,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID)
);

INSERT INTO usuarios (nombre, correo, username, password,fecha_creacion,ultimo_ingreso,usuario_activo) VALUES ('Jose Perez', 'jperez@ntt.com', 'jperez@ntt.com', '$2a$10$NWjS9lP/4spFk0dVJT4Y8e//..EqskVwTNHVJ3XotuG7LzBqYp8yG', '2024-03-12 17:00:00', '2024-03-12 17:00:00', true);
INSERT INTO PHONES (NUMBER, CITY_CODE, COUNTRY_CODE, ID_USUARIO) VALUES ('94693775', '9', '+56' , 1);


